### ISSUE TITLE
Doesn't work with non-default dockerdir

### ISSUE THREAD

**Issue by 0x46616c6b** [chadoe/docker-cleanup-volumes#10]
If you configured an alternative dockerdir (default: /var/lib/docker) the script doesn't work. It would be nice to get this variable configurable.

**Comment by chadoe** [comment]
Hi, yes that would be nice I suppose if you run the script standalone. You can also run the docker version which supports providing a custom dockerdir:

<pre>docker run -v /var/run/docker.sock:/var/run/docker.sock -v <b>/custom/path/to/your/dockerfiles</b>:/var/lib/docker --rm martin/docker-cleanup-volumes:1.5.0 --dry-run</pre>

**Comment by 0x46616c6b** [comment]
Okay, that is a nice solution!

**Comment by viatcheslavmogilevsky** [comment]
But _host_ docker daemon still show volumes path as **/custom/path/to/your/dockerfiles**.
Then all volumes do not come into `allvolumes` variable cause: https://github.com/chadoe/docker-cleanup-volumes/commit/01cbf4b3b2888be094f00aacaf6f36118c05ddf8#diff-d888d9afbf3a658746f64dc08b9a6f26R74
And finally script consider _all_ volumes to be destroy.

**Comment by chadoe** [comment]
hm you are right, that won't work currently.
