### ISSUE TITLE
Using docker binary from host through volume

### ISSUE THREAD

**Issue by viatcheslavmogilevsky** [chadoe/docker-cleanup-volumes#18]
When running from docker - there is ability to use host docker binary if we set it via host volume. For example:

``` bash
$ docker run -v $(which docker):/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker:/var/lib/docker --rm martin/docker-cleanup-volumes --dry-run
```

Looks different, but it allows to feel free which docker version is used on host and no need to keep builds for last _n_ docker versions.

**Comment by chadoe** [comment]
Yeah different version builds are unneccesary anyway,  the current 1.4.1 works for all others. I should probably update the documentation and include your solution as well.
