### ISSUE TITLE
Deleted all non-orphaned volumes

### ISSUE THREAD

**Issue by julesbravo** [chadoe/docker-cleanup-volumes#19]
Ran the docker and this just went through and deleted all volumes period even on running containers, now I get to rebuild them. Joy is me.

**Comment by chadoe** [comment]
Ouch.. but that is what the --dry-run parameter is for and why it is included by default in the examples.
Anyway, what did you run it on, which docker version, which distribution, which cleanup version, what is your docker configuration?

**Comment by tehXor** [comment]
+1 @julesbravo 
This script is very effective (or maybe a joke? :P); after running it /var/lib/docker/volumes and /var/lib/docker/vfs/dir would consume nearly no more space at all and the script doesn't seem to care if a volume is still used by one container, multiple container or even multiple running containers. Good job!

Seriously, if you are programming in such unsafe terrain you should make --dry-run the default (also I luckily did --dry-run I could understand everybody who misses it).
My docker installation is absolute standard on Ubuntu 14.04. Here is docker version:
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:35:49 UTC 2015
 OS/Arch:      linux/amd64

**Comment by chriswayg** [comment]
A very dangerous script... I'm glad I used --dry-run (which should be the default). It would have deleted lots of the wrong volumes - even from running containers.

Docker version 1.8.1, build d12ea79 on Debian Wheezy with Proxmox on ZFS
