### ISSUE TITLE
erasing running container volumes centos6 + docker 1.4.1

### ISSUE THREAD

**Issue by tobowers** [chadoe/docker-cleanup-volumes#3]
Hello!

I've noticed this script removing running container volumes on centos + docker 1.4.1 (in boot2docker)... using the docker container way to run the script.

What more information can I provide?

Topper

**Comment by korya** [comment]
Same here. CoreOS 557.2.0 with docker 1.4.1

**Comment by korya** [comment]
OK, of course. The problem is that the docker container contained 1.5.0 version of docker client. While docker daemon installed on the host is 1.4.1. As a consequence, `docker ps` failed, so `allvolumes` array was empty, hence the script removed all volumes.

**Comment by korya** [comment]
A simple solution is to make sure that docker client can communicate with the docker daemon. If it cannot, the script should fail. Something similar to:

``` sh
#!/bin/bash

set -eo pipefail

...

# Fail if server is not reachable
docker info >/dev/null

for $(docker ps -qa ...
```
