### ISSUE TITLE
Deletes bind-mount volumes that are still in use

### ISSUE THREAD

**Issue by drothlis** [chadoe/docker-cleanup-volumes#6]
From a code inspection it seems to me that this will delete bind-mount volumes from /var/lib/docker/volumes, even if they are in use.

For bind-mount volumes (that is, when you do `docker run -v /hostpath:/containerpath`), `docker inspect` prints something like this:

```
"Volumes": {
    "/containerpath": "/hostpath"
},
```

...so that volume isn't added into `allvolumes` in your script, but you do delete it from /var/lib/docker/volumes.

**Comment by chadoe** [comment]
Hi, bind-mount volumes are direct mappings and don't have volumes in /var/lib/docker/volumes afaik.

**Comment by drothlis** [comment]
They don't have anything in vfs/dir but they certainly have a config.json
under volumes/, at least on my system.

**Comment by chadoe** [comment]
Ah I see it now, interesting. Not entirely sure what those bindmount configurations are used for, everything seems to be running just fine without them here.
It's definitely going to take some time to fix as there is no reference to those directories from the inspect output.

**Comment by chadoe** [comment]
They regenerate when restarting the docker service, that at least explains why everything keeps functioning properly.
